version: '3.8'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sys?useSSL=false
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: Chicken@69
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.144:3306/sys?useSSL=false
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: Chicken@69
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

volumes:
  mysql_data:
