server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useSSL=false
    username: springstudent
    password: Chicken@69
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
